# Generated by Django 3.2.16 on 2022-12-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_bobatea', '0003_teamenu_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamenu',
            options={'verbose_name': 'Tea Menu', 'verbose_name_plural': 'Tea Menu'},
        ),
    ]
