# Generated by Django 3.2.16 on 2022-12-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_bobatea', '0006_aboutus_staffcrew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About Us', 'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='staffcrew',
            options={'verbose_name': 'Staff Crew', 'verbose_name_plural': 'Staff Crew'},
        ),
        migrations.RenameField(
            model_name='aboutus',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='staffcrew',
            name='image',
        ),
    ]
