# Generated by Django 3.2.16 on 2022-12-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_bobatea', '0007_auto_20221209_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='numer_of_guests',
            new_name='number_of_guests',
        ),
    ]
