# Generated by Django 3.2.16 on 2022-12-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_bobatea', '0008_rename_numer_of_guests_reservation_number_of_guests'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
